name: "Check branch name is compliant with conventional commits"

on:
    workflow_call:
        inputs:
            branch-name:
                required: true
                type: string

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: execute branch check script
        run: |
          chmod +x .github/scripts/branch_name_check.sh
          ./.github/scripts/branch_name_check.sh

        env:
            BRANCH_NAME: ${{ inputs.branch-name }}

        shell: bash