name: Demo | 1 - Plan - Staging

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    
    branches:
      - main

    # paths:
    #   - '**.tf'


jobs:
  check-branch-name:
    uses: ./.github/workflows/branch_name_check.yml
    with:
      branch-name: ${{ github.event.pull_request.head.ref }}